In [ ]:
#Mount the google drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# Import Necessary libraries
import os 

# Set Directory path for Dataset
os.chdir("/content/drive/My Drive/")

In [ ]:
# setting up our imports
%matplotlib inline
import pickle
from pprint import pprint
import random
import warnings
import time

import numpy as np
import pandas as pd



# **__Final 8 topic LDA**


https://colab.research.google.com/drive/1vqSNzMe6DAjFWGLRC4kwAnmNmYIRSjbC#scrollTo=xCgamKu_FVEl

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv('data_clean_en.csv') #from 8 topic LDA
df

Text_en  ... Dominant Topic
0      Highest number of Covid-19 deaths in a day. Ni...  ...              6
1      Thrown out of job, Tangail’s chamcham makers p...  ...              1
2      Coping with Covid-19 Shutdown: 200 families re...  ...              3
3      7 family members, 4 police personnel test posi...  ...              4
4      Coronavirus: Health ministry issues 13 directi...  ...              1
...                                                  ...  ...            ...
15560  The number of victims and deaths is increasing...  ...              6
15561  India returns passengers in fear of coronaviru...  ...              0
15562  Instructions to bring back the Bangladeshis tr...  ...              2
15563  Coronavirus: Control room opened in the Depart...  ...              4
15564  Coronavirus: Warning at several borders. A war...  ...              0

[15565 rows x 5 columns]

In [ ]:
df.dropna(inplace = True)
df.reset_index(drop = True, inplace=True)

In [ ]:
df

Text_en  ... Dominant Topic
0      Highest number of Covid-19 deaths in a day. Ni...  ...              6
1      Thrown out of job, Tangail’s chamcham makers p...  ...              1
2      Coping with Covid-19 Shutdown: 200 families re...  ...              3
3      7 family members, 4 police personnel test posi...  ...              4
4      Coronavirus: Health ministry issues 13 directi...  ...              1
...                                                  ...  ...            ...
15555  The number of victims and deaths is increasing...  ...              6
15556  India returns passengers in fear of coronaviru...  ...              0
15557  Instructions to bring back the Bangladeshis tr...  ...              2
15558  Coronavirus: Control room opened in the Depart...  ...              4
15559  Coronavirus: Warning at several borders. A war...  ...              0

[15560 rows x 5 columns]

In [ ]:
df['Dominant Topic'].unique()

array([6, 1, 3, 4, 2, 5, 0, 7])

In [ ]:
corpus = df['data_ready'].copy()

In [ ]:
# Creating the Bag of Words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=10000)
X = cv.fit_transform(corpus).toarray()

In [ ]:
X.shape

(15560, 10000)

In [ ]:
y=df['Dominant Topic'].values
y

array([6, 1, 3, ..., 2, 4, 0])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [ ]:
X_train.shape,y_train.shape

((12448, 10000), (12448,))

# Decision Tree

In [ ]:
## Classifier
from sklearn.tree import DecisionTreeClassifier
decision_Tree = DecisionTreeClassifier(criterion='entropy').fit(X_train, y_train)

y_pred = decision_Tree.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix
cm1 = confusion_matrix(y_test, y_pred)
cm1

array([[ 54,   8,   6,  11,  16,   3,   6,   0],
       [  7, 168,  52,  25,  30,  18,  28,   3],
       [ 10,  47, 179,  21,  57,  14,  21,   5],
       [ 18,  35,  33, 166,  50,  32,  59,  15],
       [ 11,  37,  23,  27, 764,   0, 105,   6],
       [  5,  19,  22,  27,  14,  64,  14,   5],
       [  0,  13,  15,  33,  48,   4, 486,   7],
       [  2,   9,  23,  21,  29,   4,  23,  55]])

In [ ]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

print("Accuracy score: ", accuracy_score(y_test, y_pred))
print("Recall score: ", recall_score(y_test, y_pred, average = 'weighted'))
print("Precision score: ", precision_score(y_test, y_pred, average = 'weighted'))
print("F1 score: ", f1_score(y_test, y_pred, average = 'weighted'))

dt = []
dt.append(accuracy_score(y_test, y_pred))
dt.append(recall_score(y_test, y_pred, average = 'weighted'))
dt.append(precision_score(y_test, y_pred, average = 'weighted'))
dt.append(f1_score(y_test, y_pred, average = 'weighted'))

Accuracy score:  0.622107969151671
Recall score:  0.622107969151671
Precision score:  0.6137149681004921
F1 score:  0.6137875579518131


# Random Forest

In [ ]:
from sklearn.ensemble import RandomForestClassifier
random_Forest = RandomForestClassifier(n_estimators = 10,criterion = 'entropy',  random_state = 0).fit(X_train, y_train)

In [ ]:
y_pred = random_Forest.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix
cm2 = confusion_matrix(y_test, y_pred)
cm2

array([[ 63,  12,   2,   2,  14,   2,   9,   0],
       [  3, 218,  33,  12,  42,   2,  19,   2],
       [  3,  35, 207,   9,  68,   5,  21,   6],
       [ 13,  27,  23, 214,  57,   7,  63,   4],
       [ 10,  16,   5,   6, 870,   0,  66,   0],
       [  3,  26,  29,  41,  14,  48,   8,   1],
       [  1,   2,  11,  14,  56,   1, 521,   0],
       [  2,   9,  17,  28,  32,   5,  36,  37]])

In [ ]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

print("Accuracy score: ", accuracy_score(y_test, y_pred))
print("Recall score: ", recall_score(y_test, y_pred, average = 'weighted'))
print("Precision score: ", precision_score(y_test, y_pred, average = 'weighted'))
print("F1 score: ", f1_score(y_test, y_pred, average = 'weighted'))
rf = []
rf.append(accuracy_score(y_test, y_pred))
rf.append(recall_score(y_test, y_pred, average = 'weighted'))
rf.append(precision_score(y_test, y_pred, average = 'weighted'))
rf.append(f1_score(y_test, y_pred, average = 'weighted'))

Accuracy score:  0.6998714652956298
Recall score:  0.6998714652956298
Precision score:  0.6961621493246742
F1 score:  0.6814816100298717


# Naive Bayes

In [ ]:
# Training model using Naive bayes classifier

from sklearn.naive_bayes import MultinomialNB
naive_Bayes = MultinomialNB().fit(X_train, y_train)

y_pred= naive_Bayes.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix
cm3 = confusion_matrix(y_test, y_pred)
cm3

array([[ 67,   6,   4,  10,  16,   1,   0,   0],
       [  1, 269,  13,  12,  21,  10,   4,   1],
       [  0,  13, 300,   5,  27,   3,   4,   2],
       [  2,  14,  13, 335,   8,   2,  19,  15],
       [  0,  14,   7,   5, 930,   0,  16,   1],
       [  0,   4,   8,  11,   2, 141,   1,   3],
       [  0,   2,   2,   5,  59,   2, 534,   2],
       [  0,   3,   4,   7,   3,   1,   5, 143]])

In [ ]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

print("Accuracy score: ", accuracy_score(y_test, y_pred))
print("Recall score: ", recall_score(y_test, y_pred, average = 'weighted'))
print("Precision score: ", precision_score(y_test, y_pred, average = 'weighted'))
print("F1 score: ", f1_score(y_test, y_pred, average = 'weighted'))

nb = []
nb.append(accuracy_score(y_test, y_pred))
nb.append(recall_score(y_test, y_pred, average = 'weighted'))
nb.append(precision_score(y_test, y_pred, average = 'weighted'))
nb.append(f1_score(y_test, y_pred, average = 'weighted'))

Accuracy score:  0.8737146529562982
Recall score:  0.8737146529562982
Precision score:  0.8748144844249733
F1 score:  0.8724744348868954


# KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
kNN = KNeighborsClassifier().fit(X_train, y_train)

y_pred = kNN.predict(X_test)

In [ ]:
from sklearn.metrics import confusion_matrix
cm4 = confusion_matrix(y_test, y_pred)
cm4

array([[ 59,   9,   3,   0,  21,   1,  10,   1],
       [  8, 165,  28,   5,  76,   4,  45,   0],
       [  5,  13, 158,   1, 105,   3,  68,   1],
       [ 17,  26,  22,  74, 103,   1, 160,   5],
       [  9,  12,   7,   1, 756,   0, 188,   0],
       [  5,  23,  38,   6,  34,  33,  29,   2],
       [  1,   2,   6,   0,  40,   1, 556,   0],
       [  2,   5,  10,   4,  42,   2,  64,  37]])

In [ ]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

print("Accuracy score: ", accuracy_score(y_test, y_pred))
print("Recall score: ", recall_score(y_test, y_pred, average = 'weighted'))
print("Precision score: ", precision_score(y_test, y_pred, average = 'weighted'))
print("F1 score: ", f1_score(y_test, y_pred, average = 'weighted'))

knn = []
knn.append(accuracy_score(y_test, y_pred))
knn.append(recall_score(y_test, y_pred, average = 'weighted'))
knn.append(precision_score(y_test, y_pred, average = 'weighted'))
knn.append(f1_score(y_test, y_pred, average = 'weighted'))

Accuracy score:  0.5906169665809768
Recall score:  0.5906169665809768
Precision score:  0.6405747172208905
F1 score:  0.5557086664498656


# Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
logistic_Regression = LogisticRegression().fit(X_train, y_train)

y_pred = logistic_Regression.predict(X_test)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [ ]:
from sklearn.metrics import confusion_matrix
cm5 = confusion_matrix(y_test, y_pred)
cm5

array([[ 66,   9,   4,   4,  17,   3,   1,   0],
       [  1, 267,  11,  14,  29,   4,   5,   0],
       [  2,  20, 285,   3,  30,   3,   4,   7],
       [  3,  18,  13, 299,  36,  11,  22,   6],
       [  4,  11,   9,   5, 918,   0,  25,   1],
       [  2,  11,  15,   8,  10, 119,   3,   2],
       [  0,   3,   4,   3,  36,   3, 556,   1],
       [  1,   2,   6,   7,  21,   4,  14, 111]])

In [ ]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

print("Accuracy score: ", accuracy_score(y_test, y_pred))
print("Recall score: ", recall_score(y_test, y_pred, average = 'weighted'))
print("Precision score: ", precision_score(y_test, y_pred, average = 'weighted'))
print("F1 score: ", f1_score(y_test, y_pred, average = 'weighted'))

lg = []
lg.append(accuracy_score(y_test, y_pred))
lg.append(recall_score(y_test, y_pred, average = 'weighted'))
lg.append(precision_score(y_test, y_pred, average = 'weighted'))
lg.append(f1_score(y_test, y_pred, average = 'weighted'))

Accuracy score:  0.8422236503856041
Recall score:  0.8422236503856041
Precision score:  0.8428958338696387
F1 score:  0.8393192574192979


# SVC
too time consuming

In [ ]:
# from sklearn.svm import SVC

# clf = SVC(kernel='rbf')
# clf.fit(X_train, y_train)

# y_pred = clf.predict(X_test)

In [ ]:
# from sklearn.metrics import confusion_matrix
# cm6 = confusion_matrix(y_test, y_pred)
# cm6

In [ ]:
# from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

# print("Accuracy score: ", accuracy_score(y_test, y_pred))
# print("Recall score: ", recall_score(y_test, y_pred, average = 'weighted'))
# print("Precision score: ", precision_score(y_test, y_pred, average = 'weighted'))
# print("F1 score: ", f1_score(y_test, y_pred, average = 'weighted'))

# svm = []
# svm.append(accuracy_score(y_test, y_pred))
# svm.append(recall_score(y_test, y_pred, average = 'weighted'))
# svm.append(precision_score(y_test, y_pred, average = 'weighted'))
# svm.append(f1_score(y_test, y_pred, average = 'weighted'))